Add `TournamentListView` class for Enhanced Tournament Display
uchicago-cs/chigame pull request #138
Opened 2023-11-06 00:36 UTC by jb-01

**Pull Request Description for Issue #137**

**Overview:**

This PR introduces enhancements to the `games/views.py` module in the `src/chigame` application, providing support for tournament features with a focus on listing and managing tournament-specific information.

**Key Changes:**

1. **`TournamentListView` Implementation:**
   - A new view class named `TournamentListView` has been added to handle the listing of tournaments.

2. **Tournament Matchup Queries:**
   - `TournamentListView` contains queries that fetch relevant tournament matchups. This allows for real-time display of active and forthcoming tournament games.

2023-11-13 04:50 UTC, rqueiroz20 requested changes
Great work with the tournament list view! The tournament page opens on my end and the migration went through as well. The one comment I will make is that I attempted to create a tournament object for its details to be displayed on the tournament page, but the tournament was not displayed. Perhaps I made a mistake when creating the object, but we should probably verify that tournament creation works before approving this PR.

2023-11-13 16:12 UTC, elizabethli31 requested changes
I'm also unable to view any tournaments. I think it could be because your context name is tournaments_detail, but you are feeding in tournaments? Also, please delete all the migrations from this PR along with the changes to managers.py. That's going to affect the migration merges for other teams once in dev.

2023-11-13 18:23 UTC, jb-01 commented
Hello, thanks for the feedback. I have updated `views.py` to make the tournaments observable at http://127.0.0.1:8000/games/tournaments/. Please sign in as an admin to view the list.

2023-11-13 21:54 UTC, elizabethli31 requested changes
List view is working now! I think you have the detail and create views on here which I believe is covered in another PR. Once you take those out of this PR, I can approve and merge.

2023-11-13 21:54 UTC, elizabethli31 commented on src/chigame/games/views.py
> +class TournamentCreateView(UserPassesTestMixin, CreateView):
Is this supposed to be here? I thought Create was covered by PR #187

2023-11-14 03:30 UTC, jb-01 commented
@elizabethli31 My latest commit resolves the additional views, and keeps this PR strictly related to Tournament List. The views, urls, and templates for `Create` and `Detail` were removed.

2023-11-14 03:32 UTC, elizabethli31 approved these changes
LGTM! Update with dev and I'll merge

2023-11-14 03:34 UTC, jb-01 commented
Thanks! I just updated with the Dev branch.

2023-11-14 03:38 UTC, rqueiroz20 approved these changes
The tournament list view is working properly now on my end! Thank you for addressing the comments made between myself and Elizabeth. Good job!

2023-11-14 04:34 UTC, merged

2023-11-16 04:20 UTC, jb-01 commented
Closing comment: I (jb-01) contributed to the TournamentListView in `views.py` which was heavily informed and guided by @MikeChen012345 and @MuyanXie contributions to `views.py` for Detail, Update, Delete, etc.

2023-12-09 00:43 UTC, elizabethli31 commented
Issue Score: Excellent

Comments:
Very nice work on creating a list view for tournaments. Also, great description, as it helped me identify exactly what I needed to test for the PR review.
<!-- {"score": "excellent", "minor": false} -->