matches/Updated Match and Player models to track information pertinent to match outcomes
uchicago-cs/chigame pull request #155
Opened 2023-11-07 21:30 UTC by ambr-lise

PR for Issue #109. Updated games/models.py according to the User Stories for matches. 

Player (throughtable for User and Match): 
- added team, role, outcome, and victory_type parameters to track the user's team and role (if applicable), whether the user won or withdrew, and how the user won (if applicable)

Match: 
- removed winners, which made tracking draw/withdraw/neutral outcomes more difficult (this information has essentially been migrated to Player)
- added date_played to track when the match was played

2023-11-07 22:06 UTC, jiyeongchloe approved these changes
Everything looks good to me! Is the `vicotry_type` attribute in Player implemented with specific games in mind? I'm just wondering what we'd use that for if we have an `outcome` attribute

2023-11-08 18:52 UTC, ambr-lise commented
> Everything looks good to me! Is the `vicotry_type` attribute in Player implemented with specific games in mind? I'm just wondering what we'd use that for if we have an `outcome` attribute

That's correct -- `victory_type` would essentially expand upon a "win" outcome. Certain games have different win conditions -- for example, in Root you could win via a Points Victory or a Domination Victory. However, `victory_type` is optional as many games only have one win condition. I also think it allows for some additional flexibility in case there's a game that falls outside of the win/loss/draw/withdraw outcomes.

2023-11-11 21:08 UTC, elizabethli31 requested changes
Looks good besides the one comment I made! Make sure you change that and update with dev, and I'll review again.

2023-11-11 21:08 UTC, elizabethli31 commented on src/chigame/games/models.py
> +    outcome = models.PositiveSmallIntegerField(choices=OUTCOMES)
This should be nullable in case a player is currently in a match that hasn't been completed yet.

2023-11-12 00:26 UTC, elizabethli31 approved these changes
I like the addition of a player! It makes a lot of sense to separate user from player and simplifies the match process. LGTM! I'll merge after dev changes are made.

2023-11-12 00:30 UTC, merged

2023-11-29 20:41 UTC, ambr-lise commented
Closing Statement: Added attributes for additional data tracking to Player and Match tables, and migrated some functionality from Match to Player.

2023-12-09 20:16 UTC, elizabethli31 commented
Issue Score: Excellent

Comments:
Nice work on this PR. I really like the clear distinction between what was done for the match model and player model in the description of this PR.
<!-- {"score": "excellent", "minor": false} -->