Tournaments/change notification model into announcement
uchicago-cs/chigame pull request #171
Opened 2023-11-10 03:59 UTC by MuyanXie

2023-11-11 03:02 UTC, MuyanXie commented
@MikeChen012345 Could you please take a look at this as well?

2023-11-11 04:00 UTC, MuyanXie commented
Found the user's team response to the notification model:

https://github.com/uchicago-cs/chigame/wiki/Users-&-Friending-~-Notification-Model-Documentation

2023-11-13 16:19 UTC, elizabethli31 requested changes
Generally looks good, but you have some repeats that need to be deleted. Also, please make this PR **ONLY** changes for the notification/announcement model. You have changes from your other PRs on here (all the CRUD views) which should be in the other branches. Delete those files or remove them from git for this branch. Also, I think you are not up to date with dev which has an 0006 migration, so you might need to delete this one, and re-migrate.

2023-11-13 16:19 UTC, elizabethli31 commented on src/chigame/games/models.py
> +    sender = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
Two senders (repeated code - delete one)

2023-11-13 16:19 UTC, elizabethli31 commented on src/chigame/games/models.py
>      recipients = models.ManyToManyField(User, related_name="notifications")
Delete this one on line 215.

2023-11-14 01:26 UTC, MuyanXie commented
This PR can be safely closed as I made a new PR based on the new Dev which contained most of our model logic there

2023-11-14 01:37 UTC, closed without merging