Updating the games crud pages to account for new attributes in our game model
uchicago-cs/chigame pull request #192
Opened 2023-11-12 20:36 UTC by willcravitz

This code updates the forms in the create and update pages for games to display the attributes added in #153 (things like categories, mechanics, publishers, playtime, etc.). It also adds a new game detail page to display these same attributes and includes some bootstrap styling.

2023-11-12 22:08 UTC, frowenz approved these changes
I was unable to create a Game because of the lack of selectable Category and Mechanic attributes. I worked around this by adding the following proposed changes of #179 to the GameCreateView:

```python
category = models.ManyToManyField("Category", related_name="games", blank=True)
mechanics = models.ManyToManyField("Mechanic", related_name="games", blank=True)
```

I was also able to edit the Game I created. 

I am unconvinced that the description list is a necessary addition. It seems reasonable to expect all information for a game to be viewable on a well-designed page. However, since this is more of a personal design choice, I am not going to request it be changed. 

Nice work!

2023-11-14 02:41 UTC, majorsylvie requested changes
there are now some issues with the model form, detailed in images!

the game detail view itself looks much nicer and more directly accomodates all the new fields.

<img width="472" alt="image" src="https://github.com/uchicago-cs/chigame/assets/86740254/46f9fb66-bf7a-4e49-b779-278bee0f85ab">

<img width="182" alt="image" src="https://github.com/uchicago-cs/chigame/assets/86740254/18f3222c-3db2-4468-b4b0-96f06ebb19db">

2023-11-15 00:19 UTC, ptlin25 commented
@majorsylvie I have addressed the changes you requested for the form to have better labels to give more context. The categories and mechanics attributes are now checkboxes

2023-11-15 22:35 UTC, majorsylvie approved these changes
Thank you for adding more detail to the form fields! much more readable and easy to parse.

As of now, I can still type in non number values in the BGG id field, but I am not allowed to save changes when editing if I leave it as a non-number

2023-11-15 22:35 UTC, majorsylvie commented on src/chigame/games/views.py
> +    form_class = GameForm
I would add a comment linking relevant documentation on what this `form_class` attribute is and why you are including it, since all the other views use the `fields` attribute.

2023-11-15 22:36 UTC, merged

2023-11-16 00:57 UTC, ptlin25 commented
This pull request will be closed because we have finished updating the game detail view to show the relevant attributes and updating the edit and create views to allow for the new game attributes to be added. @willcravitz redesigned the game detail view and @ptlin25 created a custom GameForm to add the new attributes and provide more context about the form fields

2023-11-25 21:55 UTC, majorsylvie commented
Issue Score: Excellent

Comments:
Great job all of you in this PR!

Descriptive summary which links relevant issue.

Thorough reviews from team members, requested feedback being taken, as well as keeping communication in the conversation. 

Great work and keep moving forward! 

<!-- {"score": "excellent", "minor": false} -->