Created a view for user's historical game information
uchicago-cs/chigame pull request #193
Opened 2023-11-12 21:35 UTC by AndrewM131

In this PR related to issue #143, we implemented a URL path to a view called user_history.html that will display the historical information of a player. It will need to be revisited to actualize the information, but this is a setup for a future task.

2023-11-12 22:14 UTC, 24raniwalar approved these changes
View, url, and template appropriately set up and extend from base. LGTM.

2023-11-13 06:08 UTC, elizabethli31 requested changes
Good work! Left a minor comment that's more or less stylistic. The only other thing I had a question on is whether historical information of a user should be visible to all users? If yes, then once you pull from dev, I can approve and merge!

2023-11-13 06:08 UTC, elizabethli31 commented on src/templates/users/user_history.html
> +    <li>Username: {{ user.name }}</li>
Because there is a username field in the model (even though it's currently set to none), I would change this to Name instead of Username.

2023-11-13 20:37 UTC, AndrewM131 commented on src/templates/users/user_history.html
> +    <li>Username: {{ user.name }}</li>
Historical information is intended to be visibile to all users. I just git pulled from dev, and will push with the style change you asked me to do.

2023-11-13 22:03 UTC, elizabethli31 approved these changes
LGTM! Good work and great job fixing the small change!

2023-11-13 22:04 UTC, merged

2023-11-14 20:16 UTC, AndrewM131 commented
Closing Statement: We have successfully created a new view that will allow any user to see another user's historical information, but the actual implemented information is yet to be incorporated. This will be returned to so that we can properly display the information.

2023-11-25 21:30 UTC, elizabethli31 commented
Issue Score: Excellent

Comments:
Nice job creating a framework for displaying historical information!

<!-- {"score": "excellent", "minor": false} -->