Added token attribute with max value of 3
uchicago-cs/chigame pull request #223
Opened 2023-11-14 20:37 UTC by 24raniwalar

We have edited the user model to add a token attribute that takes a default value of 1 and has a max value of 3. Any time it exceeds this max value it is reset to 3.

2023-11-14 20:56 UTC, MuyanXie reviewed
This looks good to me! However, I have one small concern about this. I noticed on line 43-44 in models.py, the maximum amount of token is 100 instead of 3.

2023-11-14 20:56 UTC, MuyanXie commented on src/chigame/users/models.py
> +        if self.tokens > 100:
double check this line. Maybe it should be 3 instead of 100?

2023-11-14 20:59 UTC, MuyanXie approved these changes
Great Job! Approved

2023-11-15 04:26 UTC, elizabethli31 requested changes
Migrations and model changes are solid, but you built this branch of users/inbox so it's including all changes you made on that branch. Please remove those changes and make sure this branch matches dev. This PR should only have changes in migrations and models.

2023-11-15 20:11 UTC, elizabethli31 approved these changes
LGTM! Rebase and I'll merge

2023-11-15 20:31 UTC, merged

2023-11-22 22:44 UTC, elizabethli31 commented
Issue Score: Excellent

Comments:
Good minor change. Issues and PRs should only be labeled with one team. I've removed tournaments, but next time, be sure to only label your own team.

<!-- {"score": "excellent", "minor": true} -->