Added Nested Endpoints to GET information about Game model (specifically `Categories` and `Mechanics` information)
uchicago-cs/chigame pull request #295
Opened 2023-11-27 05:23 UTC by abrahmasandra

With the updates to the `Game` model, there are now two new attributes `Mechanics` and `Categories`, that are represented as many to many relationships. This PR created two endpoint to easily GET the mechanics and categories respectively of a given game. This is very similar to the code needed to get the friends of a given user in previous issue #54. 

Endpoints created: `/api/games/<game_id>/mechanics` and `/api/games/<game_id>/categories`

In addition, I modularized the API URLs, so that the urls dealing with different models 
(Game, User, and Lobby models) are separated into sublists.

2023-11-30 18:28 UTC, cuyakonwu approved these changes
Please view my comment on the URLs, besides that all looks great!

2023-11-30 18:28 UTC, cuyakonwu commented on src/chigame/api/serializers.py
Looking wonderful so far!

2023-11-30 18:28 UTC, cuyakonwu commented on src/chigame/api/urls.py
Thank you so much for the reorganization and restructuring, if you could also take out the comments to avoid the redundancy that would also be great

2023-11-30 18:28 UTC, cuyakonwu commented on src/chigame/api/views.py
All looks great!

2023-11-30 18:41 UTC, abrahmasandra commented on src/chigame/api/urls.py
Removed the comments!

2023-11-30 19:48 UTC, cuyakonwu approved these changes
Looks Great!

2023-12-06 01:41 UTC, majorsylvie requested changes
Endpoints exist! but do not properly display multiple categories or mechanics when they are associated with a game.

Example:
consider a game:
```py
        {
            "id": 1,
            "name": "game 1",
            "description": "first game",
            "year_published": 1,
            "image": "/static/images/no_picture_available.png",
            "rules": "",
            "min_players": 1,
            "max_players": 2,
            "suggested_age": 12,
            "expected_playtime": 40,
            "min_playtime": 20,
            "max_playtime": 100,
            "complexity": "3.00",
            "BGG_id": 100,
            "categories": [
                1,
                3,
                56
            ],
            "mechanics": [
                1,
                2,
                95,
                96,
                104,
                116,
                191
            ]
        },
```
the categories endpoint returns the following:
```py
{
    "id": 1,
    "name": "Abstract Strategy",
    "description": "Abstract Strategy games are often (but not always):\n\n\n     theme-less (without storyline)\n     built on simple and/or straightforward design and mechanics\n     perfect information games\n     games that promote one player overtaking their opponent(s)\n     little to no elements of luck, chance, or random occurrence\n\n\nMicrobadges\n\n Abstract fan\n Modern abstract games fan",
    "image": "https://cf.geekdo-static.com/images/opengraph/bgg_opengraph.png"
}
```
the mechanics endpoint returns this:
```py
{
    "id": 1,
    "name": "Acting",
    "description": "Games with the Acting mechanic require players to use some form of mime or mimicry to communicate with the other players.\n\nCharades is probably the poster child for this mechanic, where one member of a team must use non-verbal clues to allow the other members to guess the solution.",
    "image": "https://cf.geekdo-static.com/images/opengraph/bgg_opengraph.png"
}
```

Only one mechanic or category when there are multiple assigned to the game.
Please fix this and actually display _all_ mechanics/categories associated with a game.
This should include pagination as the rest of your list views are paginated.

2023-12-06 01:51 UTC, abrahmasandra commented
Had a type in code making these `Retrieve` API views instead of `List` API views. Should be able to see all `Categories` and `Mechanics` corresponding to a certain `Game` object now. 

Also added Pagination support for these List Views as well

2023-12-06 01:52 UTC, majorsylvie approved these changes
I can successfully see the list of categories and mechanics when there are multiple! Thank you for taking the feedback provided.

Also, modularizing the API urls is a great idea, thank you for your effort.

2023-12-06 01:52 UTC, merged

2023-12-06 02:26 UTC, abrahmasandra commented
Closing Comment: Created two endpoints that support `GET` requests to get the `categories` or `mechanics` of a given `Game`. The specific `Game` is specified through the `game_id` within the URL.

Endpoints created: `/api/games/<game_id>/mechanics` and `/api/games/<game_id>/categories`

2023-12-08 17:42 UTC, majorsylvie commented
Issue Score: Excellent

Comments:
Happy we caught the typo!

<!-- {"score": "excellent", "minor": false} -->