Adding filtering and sorting to the game browse page and search results pages
uchicago-cs/chigame pull request #326
Opened 2023-11-30 06:20 UTC by willcravitz

This code makes some important changes:
1) Sorting and filtering have been added to the game browse page. These were implemented using custom logic added to `views.py` instead of `django-filter`.
2) Sorting and filtering work together with pagination, i.e. games are still paginated after they've been filtered and sorted.
3) Sorting and filtering were added to the search results page, which is now a game grid.
4) Pagination support was added to the search results page
5) Small style updates were made to the game detail page, including adding buttons for creating and joining a match, removing ranges if the values on each side of the range are the same, and increasing the size of complexity and players
6) Corrected a small bug from the previous merge that was preventing search upon pressing the "enter" key.

2023-11-30 22:57 UTC, ptlin25 commented
<img width="1337" alt="Screenshot 2023-11-30 at 4 52 07 PM" src="https://github.com/uchicago-cs/chigame/assets/114622027/94e127d9-cd48-4e80-90a3-1b70ad2905d6">
When I sort by name descending, lowercase names come up first. I'm not sure if this is the intended result.

2023-11-30 23:02 UTC, ptlin25 requested changes
<img width="1337" alt="Screenshot 2023-11-30 at 4 52 07 PM" src="https://github.com/uchicago-cs/chigame/assets/114622027/46ff2998-2988-4952-a429-2543cd6a5af7">
When I sort by game name descending, lower case names come up first. For example, lowercase b shows up before uppercase Z. I do not think that this should be the intended result.

2023-12-01 00:00 UTC, willcravitz commented
Thanks for pointing this out. Just pushed a change to fix it by applying `Lower` before ordering if the field is `"name"`.

2023-12-01 00:04 UTC, ptlin25 approved these changes
Thanks for making the game name sort case-insensitive. This looks good to go. Nice job implementing sorting and filtering!

2023-12-01 17:01 UTC, majorsylvie requested changes
This looks quite good! 

There are a few places where adding more code comments will make this code incredibly readable. 

Also, one thing you may want to add to the detail view is support for displaying negative values of year published nicely:

<img width="678" alt="image" src="https://github.com/uchicago-cs/chigame/assets/86740254/0b0aa352-08f8-4dfe-88dd-366be6041c7e">

could instead be 1400 BCE:
<img width="671" alt="image" src="https://github.com/uchicago-cs/chigame/assets/86740254/16109f67-3ccc-4f9b-9eee-12939da2e80e">

Beyond that, the actual functionality is great! Grid view on search results is awesome, and the filtering is well placed on the page and both quick and easy to use.

Thank you for your great work

2023-12-01 17:01 UTC, majorsylvie commented on src/chigame/games/templatetags/url_tags.py
> +@register.simple_tag(takes_context=True)
Please add code comments explaining what a `simple_tag` is and why it is needed.
Especially since IIRC this content is not covered in the course.

2023-12-01 17:01 UTC, majorsylvie commented on src/chigame/games/views.py
> +        https://docs.djangoproject.com/en/4.2/ref/models/querysets/
Nice link and docstring!

2023-12-01 17:01 UTC, majorsylvie commented on src/templates/base.html
> +                    <input id="query-input" name="query" type="text" placeholder="Search..." />
Why was this changed?

2023-12-01 17:01 UTC, majorsylvie commented on src/templates/games/game_detail.html
> +            {{ game.min_players }}–{{ game.max_players }}
Nice job adding better formatting to the case of equal min and max

2023-12-01 17:01 UTC, majorsylvie commented on src/templates/games/game_detail.html
> +        {% if game.min_playtime == game.max_playtime %}
I wonder how often this comes up? How many games have a fixed time to play.

2023-12-01 17:01 UTC, majorsylvie commented on src/templates/games/game_grid.html
> +          <option value="10+" {% if request.GET.players == '10+' %}selected{% endif %}>10+ Players</option>
Might be nice to extract some of this logic into a helper function/tag! not a huge problem to have it as is

2023-12-01 17:01 UTC, majorsylvie commented on src/templates/games/game_grid.html
> +              <p class="card-text flex-grow-1">{{ game.description|linebreaksbr|truncatewords:20 }}</p>
Why was this changed?

2023-12-01 17:01 UTC, majorsylvie commented on src/templates/games/game_grid.html
> +    // Update the filter and sorting when the user changes the dropdown
Great comment!

2023-12-01 17:35 UTC, willcravitz commented on src/templates/games/game_detail.html
> +        {% if game.min_playtime == game.max_playtime %}
Agreed that it shouldn't be very common in practice, but it was something that kept appearing in the fixtures.

2023-12-01 17:37 UTC, willcravitz commented on src/templates/base.html
> +                    <input id="query-input" name="query" type="text" placeholder="Search..." />
When the forums team updated the navbar they changed the id from `#query-input` to `#query`, which affected the event listener for submit. This change simply corrected the id name.

2023-12-01 17:40 UTC, willcravitz commented on src/templates/games/game_grid.html
> +              <p class="card-text flex-grow-1">{{ game.description|linebreaksbr|truncatewords:20 }}</p>
After looking at the documentation again, `truncate words_html` should be used when truncating text wrapped in html tags—if, for example, `game.description` itself already contained `<p>` tags. Whereas `truncatewords` is faster and used to truncate solely text, which `game.description` is.

2023-12-01 18:03 UTC, willcravitz commented on src/chigame/games/templatetags/url_tags.py
> +@register.simple_tag(takes_context=True)
Great point! Just added some comments here.

2023-12-01 18:20 UTC, willcravitz commented
Thanks for the feedback @majorsylvie! Just pushed changes to address everything.

2023-12-02 17:34 UTC, willcravitz commented on src/templates/base.html
> +                    <input id="query-input" name="query" type="text" placeholder="Search..." />
This same change was also just added by a new PR that got merged into dev, which I've now merged into this branch.

2023-12-03 17:57 UTC, majorsylvie approved these changes
Looks great thanks you for your great work and code comments. 

This is a lot of nicely formatted and commented code that brings great functionality.

Great work and keep moving forward!

2023-12-03 17:57 UTC, majorsylvie commented on src/templates/games/game_detail.html
> +            {% endif %}
works as expected!

2023-12-03 17:57 UTC, merged

2023-12-03 20:36 UTC, willcravitz commented
Closing comments: This PR added
1) Filtering and sorting to any game browse experience, search results included.
2) Pagination support on search pages and any filtered/sorted pages using a new template tag `updated_params` that preserve all old url parameters while adding new ones.
3) Formatting support on game detail pages for negative years and playtime/player ranges where the endpoints are the same.
4) All bugs with search were addressed in PR #356.

Developer contributions:
@frowenz created the logic for filtering/sorting and added nicely-styled forms to the frontend 
@willcravitz created the template tag to add pagination support and made format updates to the game detail page

2023-12-06 02:22 UTC, majorsylvie commented
Issue Score: Excellent

Comments:
Absolutely incredible work @willcravitz and @frowenz !!
This is both a very good PR for funcionality and the quality of your documentation/agile work!
Awesome summary and closing comments. Adding a numbered list of the things accomplished in the PR is great. It let's me as a reviewer easily know what to look and test for and makes it very obvious all of the things this larger PR has.

@ptlin25 great review! thank you for catching and pointing out smaller improvements like the alphabetical sort. That's exactly what the review process is for!

Be proud of the work you all have done this quarter! It is shown in PR's like this :)
<!-- {"score": "excellent", "minor": false} -->