update with chat feed scratch
uchicago-cs/chigame pull request #331
Opened 2023-11-30 18:59 UTC by MuyanXie

DRAFT to see Diff

2023-11-30 21:33 UTC, MuyanXie commented
## Testing Suggestions to Reviewers
1. Use pytest to see if the update feed API is working properly
2. Play with the frontend with send/delete feature to see it works
3. You can actually open one tab in chrome and one in safari to chat with yourself

## Using fixture

if you wish to use fixture to test this implementation [__highly recommended__], you should first run:

```
python3 manage.py loaddata tournaments-chat-fixture.json
```

After this, go to :

```
http://127.0.0.1:8000/games/tournaments/1/chat/
```

And then play with it! In this chat, there are two players in the chat; You can login using admin in one browser and using test1 in another browser to play it now:

Credentials:
email: admin@example.com PWD: pass0000
email: test1@test.com PWD: pass0000

2023-12-01 05:20 UTC, MikeChen012345 commented
Everything looks good on my end! I tried to use two browsers and tested the chat. One time I used the fixture with the admin and test1 accounts provided above, and I could send messages, receive messages from the other user, and delete my own messages (which was reflected on the end of the other user). The other time I created my own tournament through the create view and signed up two users, and it seemed that it worked fine as well. The following image was the chat history that I used in my first test with fixture:
<img width="676" alt="2699b64e2cc77fd6e933174f936eb59" src="https://github.com/uchicago-cs/chigame/assets/52188262/4088cf5e-3a20-49f4-98c5-577f764b8621">

2023-12-01 05:21 UTC, MikeChen012345 approved these changes
Everything looks good on my end! I tried to use two browsers and tested the chat. One time I used the fixture with the admin and test1 accounts provided above, and I could send messages, receive messages from the other user, and delete my own messages (which was reflected on the end of the other user). The other time I created my own tournament through the create view and signed up two users, and it seemed that it worked fine as well. The following image was the chat history that I used in my first test with the fixture:
<img width="676" alt="2699b64e2cc77fd6e933174f936eb59" src="https://github.com/uchicago-cs/chigame/assets/52188262/4088cf5e-3a20-49f4-98c5-577f764b8621">

2023-12-03 18:38 UTC, elizabethli31 requested changes
This is so cool, and the live chat works very nicely!! I left a minor comment on a stylistic choice. Also, should the chat be visible to someone who isn't logged in? Please also resolve merge conflicts for the next commit

2023-12-03 18:38 UTC, elizabethli31 commented on src/static/js/getChatUpdate.js
> +    return message.sender + ": " + `Message ${message.token_id} deleted`;
From a user perspective, it's a little confusing to have the token_id here. Deleting out of order will give something like this which is not intuitive as it seems like the "message 9 deleted" should be message 2
<img width="530" alt="image" src="https://github.com/uchicago-cs/chigame/assets/102563648/c4db878c-9193-4b17-9bbb-3fbdc3becb47">

2023-12-04 00:22 UTC, MuyanXie commented on src/static/js/getChatUpdate.js
> +    return message.sender + ": " + `Message ${message.token_id} deleted`;
Thanks for pointing that out! I've added made the delete message like "Admin: Message Deleted" without the token id here in the newest PR

2023-12-04 00:28 UTC, MuyanXie commented
Hi Elizabeth! Thanks for reviewing. I have addressed the concerns you pointed out in the newest commit. Please let me know if you more questions!

2023-12-04 07:43 UTC, elizabethli31 requested changes
Thanks for fixing the errors I pointed out! One more minor change I'd like is for there to be a redirection page if a chat object has not yet been created. I know you have a PR open to automatically create one when a tournament is created, but it's still good practice to handle the error in case something goes wrong with the creation. Right now, I'm able to go to tournaments/pk/chat even if that tournament does not have a chat object. It just doesn't allow me to send any messages. Please redirect the user back to the tournamnent details page with an error saying something like "chat does not exist" when this happens, so they aren't able to access that page.

2023-12-04 08:11 UTC, MuyanXie commented
Thanks for pointing that out! I have made the changes accordingly, and please let us know if there are other problems!

2023-12-04 18:32 UTC, elizabethli31 approved these changes
Great work finishing up the last PR in the chat series! This was a huge endeavor to create a live chat, and it's working so well. This PR looks good to go, so I will approve and merge. But please make note in your final report and some Wiki documentation about the mock chat that is currently still in place (for tournament 1). I'm fine with it being there for the purposes of your demo, but it shouldn't in the future.

2023-12-04 18:35 UTC, elizabethli31 commented
Actually sorry ignore my comment about the mock messages - I just realized those were part of your fixture. Great work!

2023-12-04 18:35 UTC, merged

2023-12-04 20:27 UTC, MuyanXie commented
Closing Statement:

@MuyanXie worked on coding the frontend and API. @MikeChen012345 worked on reviewing the code and pointing out inefficiencies. @rqueiroz20 worked on peer programming with Sam on the API.

2023-12-10 22:37 UTC, elizabethli31 commented
Issue Score: Excellent

Comments:
Nice work again on this massive feature. Super cool seeing it work - you guys did a great job!
<!-- {"score": "excellent", "minor": false} -->