Added tests for getting game lists using serializers and the api-game…
uchicago-cs/chigame pull request #336
Opened 2023-11-30 19:42 UTC by giomhern

…-list URL

2023-11-30 19:49 UTC, cuyakonwu approved these changes
Looks great, and is passing well!

2023-12-03 21:23 UTC, cuyakonwu approved these changes
Passes all tests and looks good!

2023-12-07 20:06 UTC, majorsylvie requested changes
Nice additions, appreciate the import comments, think they work well.

Please add more body to a code comment but otherwise this is good to merge!

2023-12-07 20:06 UTC, majorsylvie commented on src/chigame/api/tests/test_api.py
> +                # Use key indexing for dictionaries and ReturnDict
This should include a why in the code comment. 
Why use/need key indexing for what attriutes.

2023-12-07 21:23 UTC, majorsylvie approved these changes
Fantastic code comment! 

Thank you for adding more tests.

With feedback addressed this is good to go.

Thank you for your work

2023-12-07 21:23 UTC, majorsylvie commented on src/chigame/api/tests/test_api.py
> +            # which would fail due to type mismatch despite representing the same value.
Absolutely fantastic code comment.
Clear, direct, justified, with an example to boot!

Thank you for your work

2023-12-07 21:24 UTC, merged

2023-12-07 21:32 UTC, giomhern commented
This PR, rooted in Issue #327, was focused on enhancing and ensuring that our GET API endpoint for games and the associated factory worked up to standards. Previously, we had an issue of mismatched values within the serialized and unserialized data which would cause the tests to fail. This has now been resolved in the helper function ``` check_equal ``` and the tests pass wonderfully!

Thank you to @giomhern for coding up the tests and @cuyakonwu for the help reviewing!

2023-12-07 21:47 UTC, majorsylvie commented
Issue Score: Excellent

Comments:
Great work!
Very very good closing comment.

<!-- {"score": "excellent", "minor": false} -->