Added whoosh search backend and realtime indexing
uchicago-cs/chigame pull request #342
Opened 2023-12-01 00:26 UTC by joshuamonroe

Per issue #325, I've enabled the much more robust whoosh search backend in django-machina, with realtime indexing enabled so that we don't have run `python3 mangage.py update_index` every time the forum content changes. Note, that you will still need to run this command once to index any pre-existing forum content.

This backend generates index files which are stored in `src/chigame/forums/search_index`. I've added this directory to `.gitignore` and while I was in there I also added the `.vscode` settings directory.

2023-12-01 00:37 UTC, Benjoman12 approved these changes
This looks good to me as it both cleanly adds the necessary items and adds clarity to the settings file regarding the django-machina related items.

2023-12-01 18:58 UTC, majorsylvie requested changes
Overall, excited to see changes like this!

Please add more comments explaining your code, specific guidance in-review comments.

FYI, it looks like the actual search only uses full-string matches instead of substring:

<img width="1092" alt="image" src="https://github.com/uchicago-cs/chigame/assets/86740254/b34b2221-0971-496d-a4bb-9f835c5e1ad3">

<img width="1047" alt="image" src="https://github.com/uchicago-cs/chigame/assets/86740254/1e565890-58f2-410d-9659-7629199f62fc">

<img width="1047" alt="image" src="https://github.com/uchicago-cs/chigame/assets/86740254/f4731d63-69d9-4f98-afcf-de26333b7a79">
<img width="1060" alt="image" src="https://github.com/uchicago-cs/chigame/assets/86740254/d4f24800-47d8-4a68-9eaa-4d5dd5dd9937">
<img width="904" alt="image" src="https://github.com/uchicago-cs/chigame/assets/86740254/44b80248-53f3-4da8-a9f5-f9b4bf8a2557">

You could consider adding substring search support, though I do not know what that would take in terms of indexing.

Please add further comments and then this PR should be good to go!

2023-12-01 18:58 UTC, majorsylvie commented on src/config/settings/base.py
> +# https://django-haystack.readthedocs.io/en/latest/signal_processors.html
I would add a comment briefly mentioning what a "signal processor" is and why you chose this one.

2023-12-01 18:58 UTC, majorsylvie commented on .gitignore
> +# Django-machina whoosh search index
I would add a comment basically saying what you did in the summary that files are generated by the indexer and put here based on the settings. 

Please link to relevant documentation, expand on why this is the specific directory, and why it should be in the gitignore

2023-12-01 18:58 UTC, majorsylvie commented on .gitignore
> +# Visual Studio Code
similar to below, add a comment explaining what files vscode generates that we don't want in git.

2023-12-02 18:19 UTC, joshuamonroe commented
@majorsylvie I've added the additional documentation that you requested.

Good catch on the substring matching. I looked into it quickly and, although I couldn't find anything definitive on how to implement it, it does look like it would likely require changing how content is indexed in django-machina. I can create an issue in the backlog for future devs to address this.

2023-12-03 18:48 UTC, majorsylvie approved these changes
Absolutely incredibly job with the code comments. 
Very descriptive, focused, clearly written, with proper references to documentation and relevant concepts.

Phenomenal work! 
This is good to merge and wonderful work.

2023-12-03 18:48 UTC, majorsylvie commented on .gitignore
> +# Visual Studio Code
phenomenal comment!

2023-12-03 18:48 UTC, majorsylvie commented on .gitignore
> +#   settings/base.py > DJANGO-MACHINA SETTINGS > HAYSTACK_CONNECTIONS > "PATH"
Incredibly descriptive and relevant comment. Wonderful job!

2023-12-03 18:48 UTC, majorsylvie commented on src/config/settings/base.py
> +# https://django-haystack.readthedocs.io/en/latest/signal_processors.html
Please make an issue for this queued search and put it in the backlog!

2023-12-03 18:48 UTC, merged

2023-12-05 21:20 UTC, joshuamonroe commented
I've added the following issue to implement queued search at a later date.
- #416 

Thanks to @Benjoman12 for reviewing the PR.

2023-12-08 17:57 UTC, majorsylvie commented
Issue Score: Excellent

<!-- {"score": "excellent", "minor": false} -->