Integration of Placeholder Game + Match Start Conditions Implemented
uchicago-cs/chigame pull request #345
Opened 2023-12-01 07:28 UTC by nugerhard

This is a 2 (probably 3) issue pr: Essentially, what I've done is I have made the placeholder game accessible from any particular lobby page. But, it only becomes accessible once the lobby conditions have been met. To this end, I've integrated a timer related to the lobby model onto the lobby detail page using an AJAX function: once this timer has expired, and sufficient users are in the lobby, the lobby allows the user to play the game. More notes to come, likely on the relevant issues.

2023-12-02 23:32 UTC, nugerhard commented
Apologies, added some small last-minute stuff: when the timer ran out, page did not reflect changes until it was reloaded. So, when the update function is now called, the page is refreshed. Also, did a bit of shuffling of the html on the lobby details page to make it look nicer.

2023-12-03 20:34 UTC, jiyeongchloe approved these changes
Everything works as expected! Good job implementing the match status change that we talked about and integrating the dummy game! We might want to make a new issue for future teams for making sure that the game link corresponds with the user's game of choice.

2023-12-04 08:25 UTC, elizabethli31 requested changes
Timer is really really neat and works beautifully! Also, the real time change to the lobby closed message is so sick. I left a few minor change requests. It's a bit beyond the scope of this PR, so if it proves to be too much to add the different match finished outcomes, just let me know. Really great work Nat!

2023-12-04 08:25 UTC, elizabethli31 commented on src/templates/games/game_coinresult.html
> +    <a href="{% url 'lobby-list' %}">Back to Lobbies</a>
Intuitively, it makes more sense for this to redirect back to the lobby detail page that the game was started from. I think this would be easier for your demo too, so that you can see the match status after the game has been played.

2023-12-04 08:25 UTC, elizabethli31 commented on src/chigame/games/views.py
> +    if match.players.all().count() == lobby.members.all().count():
Logic is a little too simple right now, and I don't love that this automatically leads to the "match is finished or cancelled" option. I don't think it would be too difficult to check separately if the lobby members count is less than min players just to distinguish the match status comment a little.

2023-12-04 08:25 UTC, elizabethli31 commented on src/templates/games/lobby_details.html
> +        //console.log("lobby_created:", "{{ lobby_detail.lobby_created }}");
Remove these print statements!

2023-12-04 17:37 UTC, nugerhard commented on src/templates/games/game_coinresult.html
> +    <a href="{% url 'lobby-list' %}">Back to Lobbies</a>
Implemented

2023-12-04 17:39 UTC, nugerhard commented on src/chigame/games/views.py
> +    if match.players.all().count() == lobby.members.all().count():
I definitely agree, I think the match_status field should maybe eventually get a fourth–match cancelled–option. For the time being, I am running a frontend check on whether a match met conditions to start or not, on the lonny_details.html page.

2023-12-04 17:39 UTC, nugerhard commented on src/templates/games/lobby_details.html
> +        //console.log("lobby_created:", "{{ lobby_detail.lobby_created }}");
Fixed.

2023-12-04 19:54 UTC, elizabethli31 requested changes
Thanks for addressing my changes! One last thing I didn't catch earlier, but currently only once the match has been invoked will the status be updated on the lobby list page. If the match was cancelled due to insufficient players the match status will still show up as lobbied from the list page. For example, Dragon's Lair
<img width="1041" alt="image" src="https://github.com/uchicago-cs/chigame/assets/102563648/0d44a1da-496d-4c66-94be-45880c078459">
<img width="477" alt="image" src="https://github.com/uchicago-cs/chigame/assets/102563648/cc9743f3-2476-4b00-9cbe-87d5300fff5b">
The status updates fine from the list view when the match is actually completed.

2023-12-04 19:54 UTC, elizabethli31 commented on src/templates/games/lobby_details.html
> +            console.log(data);
Can you remove this print too

2023-12-04 21:29 UTC, elizabethli31 approved these changes
LGTM! Again, great work on this PR and thanks for addressing my comments.

2023-12-04 21:29 UTC, merged

2023-12-06 22:48 UTC, nugerhard commented
Closing Statement: This PR was definitely down to the wire, apologies. But the placeholder game and the lobby_details page are now connected. And, the timer is as robust as it can be (so long as it can only exist on one page, say lobby_details). 

Here's a bit more color on the sqlite issue, from a conversation on Slack between me, Elizabeth, and Chloe: The database can't calculate the values independently. So, the script at the bottom of our lobbies page has to run in order for the match_status to update. I figured, rather than adding a script at the bottom of the lobby list page which runs a timer check for each of the lobbies on the page (and reloads the when any one runs out), it would be better to have the non-updated lobby status displayed on the page.

2023-12-10 22:54 UTC, elizabethli31 commented
Issue Score: Excellent

Comments:
Very large PR that provided much more functionality to matches - great work!
<!-- {"score": "excellent", "minor": false} -->