Forum Advanced Search Integration
uchicago-cs/chigame pull request #358
Opened 2023-12-01 20:37 UTC by Benjoman12

Per issue #310, the forum's advanced search bar capability has been integrated into the search bar.

2023-12-01 20:39 UTC, Benjoman12 commented
This commit is based on the changes that will be made through PR #309. So once that PR is approved the changes that this makes will only be relevant to the base.html file.

2023-12-04 03:21 UTC, joshuamonroe requested changes
One small change requested. Otherwise, this looks good to me from a code perspective, although I'm not certain I'm in love with it from a UI perspective. It works for now, but the way it appears and disappears, I could see it becoming a pain point later on when the nav bar layout starts to become more resolved. However, once that change is made, I'll approve it and we'll let @majorsylvie weigh in.

2023-12-04 03:21 UTC, joshuamonroe commented on src/chigame/games/views.py
> -
Although this doesn't appear to do any harm, it also isn't necessary to modify this file. Let's keep the PR clean by removing this change.

2023-12-04 23:01 UTC, joshuamonroe approved these changes
Thanks for cleaning that up, approved.

2023-12-05 01:31 UTC, majorsylvie requested changes
There is a section that I would love a code comment on!

I appreciate how you can still use the general search bar as well as the Advanced Search UI!

I was able to search and get matches from post descriptions and titles!

This is a great feature to bring in! Thank you for your work.

Please add the code comment then this is good to merge.

2023-12-05 01:31 UTC, majorsylvie commented on src/templates/base.html
> +            if (query_type.value === "forums") {
Please add a code comment explaining the purpose of this `classList` editing.

2023-12-05 16:28 UTC, majorsylvie approved these changes
Thank you for adding the code comment! Now that code is much easier to immediately understand.

Let's merge this cool searching!

2023-12-05 16:28 UTC, merged

2023-12-05 21:18 UTC, Benjoman12 commented
Closed and merged to dev without significant revision. Thanks to @joshuamonroe for reviewing the PR.

2023-12-08 17:56 UTC, majorsylvie commented
Issue Score: Excellent

<!-- {"score": "excellent", "minor": false} -->