Created API Endpoints to GET List of Users from User Group and vice versa
uchicago-cs/chigame pull request #375
Opened 2023-12-02 03:40 UTC by abrahmasandra

In this PR, we created an endpoint that will GET all of the groups that a given user is in. In addition, another endpoint was created that can GET all of the members of a given group. These endpoints will only support GET requests. They are clearly important, as an API user may want to get information relating `Users` to `Groups`

We support a `GET` request to the endpoint: `/api/users/<user_id>/groups` to get the groups from a given user. This endpoint allows us to specify the user through the `user_id`, and then we can look up the groups of this user. 

We also support a `GET` request to the endpoint: `/api/groups/<group_id>/members` to get all the users/members of a given group. This endpoint allows us to specify the group through the `group_id`, and then we can look up the members of the group.

2023-12-03 21:21 UTC, cuyakonwu approved these changes
Looks Great! I love the consistency and organization

2023-12-03 21:21 UTC, cuyakonwu commented on src/chigame/api/urls.py
It might be worth putting the URLs in a variable and then putting them in the path like the other URLs

2023-12-05 17:27 UTC, majorsylvie approved these changes
Looks great and both endpoints work! 

Please add support for slugs when doing user lookup! 
This should also be done for the friends endpoint, though that should have another issue / PR opened for in in the `2023/wrap-up` milestone.

Please at least add support for username slugs when going to `users/<username_slug>/groups`

Then this will be good to merge!

2023-12-05 17:28 UTC, majorsylvie requested changes
Meant to request changes!

---

Looks great and both endpoints work! 

Please add support for slugs when doing user lookup! 
This should also be done for the friends endpoint, though that should have another issue / PR opened for in in the `2023/wrap-up` milestone.

Please at least add support for username slugs when going to `users/<username_slug>/groups`

Then this will be good to merge!

2023-12-05 20:02 UTC, abrahmasandra commented
Slug functionality for `users/<username_slug>/groups` implemented. Also refactored the `slug` checking/lookup into a separate helper function called `get_user`

2023-12-06 00:04 UTC, majorsylvie approved these changes
Thank you for adding the slug functionality for the `/api/users/<username>/groups` endpoint!

Given that you've addressed the feedback, this is good to merge now.

2023-12-06 00:04 UTC, majorsylvie commented on src/chigame/api/views.py
> +def get_user(lookup_value):
Good job modularizing this into a helper function

2023-12-06 00:04 UTC, merged

2023-12-06 00:40 UTC, abrahmasandra commented
Closing Comment:

In this PR, we implemented the endpoint `/api/users/<slug>/groups`, which supports `GET` requests and returns back all of the groups that the `user` corresponding with the given `slug` is a part of. The `slug` can either be the `user_id` or the `username` of the `User`. We also implemented the endpoint `/api/groups/<group_id>/members` in order to get all the `User` objects that are a part of a certain `Group`, specified by the `group_id`

2023-12-08 17:35 UTC, majorsylvie commented
Issue Score: Excellent

Comments:
Nice work! Good closing comment.

<!-- {"score": "excellent", "minor": false} -->